version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tamag
    volumes:
      - db-data:/var/lib/mysql

  feedservice:
    image: ghcr.io/nawinscf/feedservice:latest
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  tamagoservice:
    image: ghcr.io/nawinscf/tamagoservice:latest
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  tamago-front:
    image: ghcr.io/nawinscf/tamago-front:latest
    ports:
      - "3000:3000"
    environment:
      # disable Next.js telemetry in production by default
      NEXT_TELEMETRY_DISABLED: 1
    depends_on:
      - tamagoservice
      - feedservice

volumes:
  db-data:
