version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tamag
    volumes:
      - db-data:/var/lib/mysql

  feedservice:
    image: ghcr.io/nawinscf/feedservice:latest
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  tamagoservice:
    image: ghcr.io/nawinscf/tamagoservice:latest
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  tamago-front:
    image: ghcr.io/nawinscf/tamago-front:latest
    # Build the front image on the host so Next is compiled with the correct
    # INTERNAL_* build args (rewrites are baked at build-time). This is useful
    # when deploying to an environment that can build the image locally (EC2).
    build:
      context: ./tamago-front
      args:
        # Optional token for private npm installs
        NPM_TOKEN: ${NPM_TOKEN}
        # Public client-visible URLs (usually empty in prod to keep relative requests)
        NEXT_PUBLIC_FEEDSERVICE_BASE: ${NEXT_PUBLIC_FEEDSERVICE_BASE:-}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-}
        NEXT_PUBLIC_TAMAGOSERVICE_BASE: ${NEXT_PUBLIC_TAMAGOSERVICE_BASE:-}
        # INTERNAL_* are used by Next during the build to create server-side rewrites
        INTERNAL_FEEDSERVICE_BASE: ${INTERNAL_FEEDSERVICE_BASE:-http://feedservice:8080}
        INTERNAL_TAMAGOSERVICE_BASE: ${INTERNAL_TAMAGOSERVICE_BASE:-http://tamagoservice:8080}
    ports:
      - "3000:3000"
    environment:
      # disable Next.js telemetry in production by default
      NEXT_TELEMETRY_DISABLED: 1
      # Client-visible (public) URLs should be set to real public endpoints (load balancer / domain).
      # Leave NEXT_PUBLIC_* empty so the client uses relative requests to the Next server (recommended),
      # and configure internal service addresses below for server-side rewrites.
      NEXT_PUBLIC_FEEDSERVICE_BASE: "${NEXT_PUBLIC_FEEDSERVICE_BASE:-}"
      NEXT_PUBLIC_API_BASE_URL: "${NEXT_PUBLIC_API_BASE_URL:-}"
      NEXT_PUBLIC_TAMAGOSERVICE_BASE: "${NEXT_PUBLIC_TAMAGOSERVICE_BASE:-}"
      # Internal service addresses used by the Next server at runtime/build (NOT exposed to browser)
      INTERNAL_FEEDSERVICE_BASE: "${INTERNAL_FEEDSERVICE_BASE:-http://feedservice:8080}"
      INTERNAL_TAMAGOSERVICE_BASE: "${INTERNAL_TAMAGOSERVICE_BASE:-http://tamagoservice:8080}"
    depends_on:
      - tamagoservice
      - feedservice

volumes:
  db-data:
