# version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tamag
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  feedservice:
    build: ./feedservice
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
      # JWT secret must match the one used by tamagoservice so services can verify access tokens
      APP_JWT_SECRET: "Bm8wDVLQ22jJNamsqbpEIvxyn7jFnmeXTfwbCmVt29Q="
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tamag?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./tamagoservice/IMG:/app/IMG
    depends_on:
      - db

  tamagoservice:
    build: ./tamagoservice
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      # Enable DEBUG logging for Spring MVC and request mapping to help diagnose missing controller mappings
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_SERVLET: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_SERVLET_HANDLER: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_SERVLET_DISPATCHER: DEBUG
      # JWT secret (generated locally) - keep this out of source control in production
      APP_JWT_SECRET: "Bm8wDVLQ22jJNamsqbpEIvxyn7jFnmeXTfwbCmVt29Q="
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tamag?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./tamagoservice/IMG:/app/IMG
    depends_on:
      - db

volumes:
  db-data: