import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../src/context/AuthContext';
import NavBar from '../components/NavBar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NavBar />
          {/* responsive 3-column layout: gutters on large screens, single column on small screens */}
          <div className="px-4 sm:px-6 lg:px-8 py-8">
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
              <div className="hidden lg:block lg:col-span-2" />
              <div className="col-span-1 lg:col-span-8 mx-auto max-w-4xl w-full">
                {children}
              </div>
              <div className="hidden lg:block lg:col-span-2" />
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
