/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  /*
    If some classes used in client components aren't being generated by Tailwind's
    content scanner (e.g. when using dynamic class construction or tooling edge-cases),
    add them to safelist so they're always emitted during dev/build.
  */
  safelist: [
    'text-red-600', 'bg-white', 'shadow', 'p-4', 'px-3', 'py-1', 'border', 'rounded', 'w-full', 'justify-between'
  ],
  plugins: [],
}
